### ISSUE TITLE
Add toggle to make the configuration "out of" instead of "to" a segment.

### ISSUE THREAD

**Issue by fmichea** [fmichea/LiveSplit.SegmentedBPT#1]

**Comment by C0mposer** [comment]
I would also appreciate this!

**Comment by fmichea** [comment]
This has been implemented now in latest version. There is a checkbox now that allows making the "Alias" for each selected split a "Full Alias" meaning nothing will be prepended to it. This means it's possible to make the alias "BPT out of ..." and toggle that checkbox to take full control of what is displayed.
